{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{let content_data= ng_json_decode($attribute.data_text)}

{if is_set( $content_data.id )}
    {if eq($content_data.type, 'internal')}
        {if and( $attribute.content, or( $attribute.content.can_read, $attribute.content.can_view_embed ), $attribute.content.has_visible_node )}
            {content_view_gui view=text_linked content_object=$attribute.content}
            <p>
                {'Type'|i18n( 'design/standard/content/datatype' )}: {$content_data.type},
                {'Target'|i18n( 'design/standard/content/datatype' )}: {$content_data.target},
                {'Label'|i18n( 'design/standard/content/datatype' )}: {$content_data.label},
                {'Suffix'|i18n( 'design/standard/content/datatype' )}: {$content_data.suffix}
            </p>
        {else}
            {'No relation'|i18n( 'design/standard/content/datatype' )}
        {/if}
    {/if}

    {if eq($content_data.type, 'external')}
        {* DO NOT EDIT THIS FILE! Use an override template instead. *}
        <a href="{$attribute.content}">{$attribute.content}</a>
        <p>
            {'Type'|i18n( 'design/standard/content/datatype' )}: {$content_data.type},
            {'Target'|i18n( 'design/standard/content/datatype' )}: {$content_data.target},
            {'Label'|i18n( 'design/standard/content/datatype' )}: {$content_data.label}
        </p>
    {/if}
{else}
    {'Empty enhanced link'|i18n( 'design/standard/content/datatype' )}
{/if}
