{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{let content=$class_attribute.content}

{* Allowed link type. *}
<div class="block">
    <label>{'Allowed link type'|i18n( 'design/standard/class/datatype' )}:</label>
    <p>{$content.allowedLinkType}</p>
</div>

<div class="block">
    <h3>{'Internal link options'|i18n( 'design/standard/class/datatype' )}:</h3>
    {* Allowed classes. *}
    <div class="block inline">
        <label>{'Allowed classes'|i18n( 'design/standard/class/datatype' )}:</label>
        {section show=$content.selectionContentTypes|count|lt( 1 )}
        <p>{'Any'|i18n( 'design/standard/class/datatype' )}</p>
        {section-else}
            <ul>
                {section var=Classes loop=$content.selectionContentTypes}<li>{$Classes.item}</li>{/section}
            </ul>
        {/section}
    </div>

    {* Allowed internal targets. *}
    <div class="block inline">
        <label>{'Allowed internal targets'|i18n( 'design/standard/class/datatype' )}:</label>
        <ul>
            {section var=Classes loop=$content.allowedTargetsInternal}<li>{$Classes.item}</li>{/section}
        </ul>
    </div>

    {* Enable suffix. *}
    <div class="block inline">
        <label>{'Enable suffix'|i18n( 'design/standard/class/datatype' )}:</label>
        <p>{if $content.enableSuffix eq true}true{else}false{/if}</p>
    </div>
</div>

<div class="block">
    <h3>{'External link options'|i18n( 'design/standard/class/datatype' )}:</h3>

    {* Allowed external targets. *}
    <div class="block inline">
        <label>{'Allowed external targets'|i18n( 'design/standard/class/datatype' )}:</label>
        <ul>
            {section var=Classes loop=$content.allowedTargetsExternal}<li>{$Classes.item}</li>{/section}
        </ul>
    </div>
</div>

{/let}
