{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{default attribute_base=ContentObjectAttribute}
{let class_content=$attribute.contentclass_attribute.content}
{let content_data= ng_json_decode($attribute.data_text)}

{if ne( $attribute_base, 'ContentObjectAttribute' )}
    {def $id_base = concat( 'ezcoa-', $attribute_base, '-', $attribute.contentclassattribute_id, '_', $attribute.contentclass_attribute_identifier )}
{else}
    {def $id_base = concat( 'ezcoa-', $attribute.contentclassattribute_id, '_', $attribute.contentclass_attribute_identifier )}
{/if}

<div class="block">
    <label for="ecael_type_{$attribute.contentclass_attribute.id}">{'Link type'|i18n( 'design/standard/class/datatype' )}:</label>
    <select id="eccael_types_{$attribute.contentclass_attribute.id}" name="ContentClass_ngenhancedlink_link_type_{$attribute.contentclass_attribute.id}">
        <option value="0" {eq( $content_data.type, 'internal' )|choose( '', 'selected="selected"' )} >{'Internal'|i18n( 'design/standard/class/datatype' )}</option>
        <option value="1" {eq( $content_data.type, 'external' )|choose( '', 'selected="selected"' )}>{'External'|i18n( 'design/standard/class/datatype' )}</option>
    </select>
</div>

<div class="block internal-link-block">
    <h2>{'Internal link'|i18n( 'design/standard/class/datatype' )}:</h2>

    <div class="block" id="ngenhancedlink_browse_{$attribute.id}">

        <table class="list{if $attribute.content|not} hide{/if}" cellspacing="0">
            <thead>
            <tr>
                <th>{'Name'|i18n( 'design/standard/content/datatype' )}</th>
                <th>{'Name'|i18n( 'design/standard/content/datatype' )}</th>
                <th>{'Type'|i18n( 'design/standard/content/datatype' )}</th>
                <th>{'Section'|i18n( 'design/standard/content/datatype' )}</th>
                <th>{'Published'|i18n( 'design/standard/content/datatype' )}</th>
            </tr>
            </thead>
            <tbody>
            <tr class="bglight">
                {if $attribute.content}

                    {* Name *}
                    <td>{$attribute.content.name|wash()}</td>

                    {* Type *}
                    <td>{$attribute.content.class_name|wash()}</td>

                    {* Section *}
                    <td>{fetch( section, object, hash( section_id, $attribute.content.section_id ) ).name|wash}</td>

                    {* Published. *}
                    <td>{if $attribute.content.status|ne( 1 )}
                            {'No'|i18n( 'design/standard/content/datatype' )}
                        {else}
                            {'Yes'|i18n( 'design/standard/content/datatype' )}
                        {/if}
                    </td>
                {else}
                    <td>--name--</td>
                    <td>--class-name--</td>
                    <td>--section-name--</td>
                    <td>--published--</td>
                {/if}
            </tr>
            </tbody>
        </table>

        {if $attribute.content|not}
            <p class="ezobject-relation-no-relation">{'There are no related objects.'|i18n( 'design/standard/content/datatype' )}</p>
        {/if}

        <div class="block inline-block">
{*            {if $attribute.class_content.default_selection_node}
                <input type="hidden" name="{$attribute_base}_browse_for_object_start_node[{$attribute.id}]" value="{$attribute.class_content.default_selection_node|wash}" />
            {/if}*}
            {if is_set( $class_content.selectionContentTypes[0] )}
                <input type="hidden" name="{$attribute_base}_browse_for_object_class_constraint_list[{$attribute.id}]" value="{$class_content.selectionContentTypes|implode(',')}" />
            {/if}
            {if $attribute.content }
                <input class="button ezobject-relation-remove-button" type="submit" name="CustomActionButton[{$attribute.id}_remove_object]" value="{'Remove object'|i18n( 'design/standard/content/datatype' )}" />
            {else}
                <input class="button-disabled ezobject-relation-remove-button" type="submit" name="CustomActionButton[{$attribute.id}_remove_object]" value="{'Remove object'|i18n( 'design/standard/content/datatype' )}" disabled="disabled" />
            {/if}
        </div>
        <h4>{'Add an object in the relation'|i18n( 'design/standard/content/datatype' )}</h4>
        <div class="left">
            <input type="hidden" name="{$attribute_base}_data_object_relation_id_{$attribute.id}" value="{if eq($content_data.type, 'internal')}{$attribute.data_int}{/if}" />
            {if $attribute.content }
                <input class="button-disabled ezobject-relation-add-button" type="submit" name="CustomActionButton[{$attribute.id}_browse_object]" value="{'Add an existing object'|i18n( 'design/standard/content/datatype' )}" title="{'Browse to add an existing object in this relation'|i18n( 'design/standard/content/datatype' )}" disabled="disabled" />
                {*
                    {include uri='design:content/datatype/edit/ngenhancedlink_ajaxuploader.tpl' enabled=false()}
                *}
            {else}
                <input class="button ezobject-relation-add-button" type="submit" name="CustomActionButton[{$attribute.id}_browse_object]" value="{'Add an existing object'|i18n( 'design/standard/content/datatype' )}" title="{'Browse to add an existing object in this relation'|i18n( 'design/standard/content/datatype' )}" />
                {*
                    {include uri='design:content/datatype/edit/ngenhancedlink_ajaxuploader.tpl' enabled=true()}
                *}
            {/if}

        </div>
        <div class="right">
            <input type="text" class="halfbox hide ezobject-relation-search-text" />
            <input type="submit" class="button hide ezobject-relation-search-btn" name="CustomActionButton[{$attribute.id}_browse_object]" value="{'Find object'|i18n( 'design/standard/content/datatype' )}" />
        </div>
        <div class="break"></div>
        <div class="block inline-block ezobject-relation-search-browse hide"></div>
        {include uri='design:content/datatype/edit/ngenhancedlink_ajax_search.tpl'}
    </div>

    <div class="block inline-block">
        <label for="{$id_base}_suffix">{'Suffix'|i18n( 'design/standard/content/datatype' )}:</label>
        <input id="{$id_base}_suffix" class="box ezcc-{$attribute.object.content_class.identifier} ezcca-{$attribute.object.content_class.identifier}_{$attribute.contentclass_attribute_identifier}" type="text" size="70" name="{$attribute_base}_ngenhancedlink_suffix_{$attribute.id}" {if not($attribute.contentclass_attribute.content.enableSuffix) }disabled="disabled"{/if} {if eq($content_data.type, 'internal')}value="{$content_data.suffix|wash( xhtml )}"{/if} />
    </div>

    {* Text. *}
    <div class="block inline-block">
        <label for="{$id_base}_internal_label">{'Label'|i18n( 'design/standard/content/datatype' )}:</label>
        <input id="{$id_base}_internal_abel" class="box ezcc-{$attribute.object.content_class.identifier} ezcca-{$attribute.object.content_class.identifier}_{$attribute.contentclass_attribute_identifier}" type="text" size="70" name="{$attribute_base}_ngenhancedlink_label_internal_{$attribute.id}" {if eq($content_data.type, 'internal')}value="{$content_data.label|wash( xhtml )}"{/if} />
    </div>

    <label for="eccael_target_{$attribute.contentclass_attribute.id}">{'Target'|i18n( 'design/standard/class/datatype' )}:</label>
    <select id="eccael_target_{$attribute.contentclass_attribute.id}" name="ContentClass_ngenhancedlink_target_internal_{$attribute.contentclass_attribute.id}">
        <option value="0" {if not($attribute.contentclass_attribute.content.allowedTargetsInternal|contains('link'))}disabled="disabled"{/if} {eq( $content.link_type, 0 )|choose( '', 'selected="selected"' )}>{'Link'|i18n( 'design/standard/class/datatype' )}</option>
        <option value="1" {if not($attribute.contentclass_attribute.content.allowedTargetsInternal|contains('link_in_new_tab'))}disabled="disabled"{/if} {eq( $content.link_type, 1 )|choose( '', 'selected="selected"' )}>{'Link in new tab'|i18n( 'design/standard/class/datatype' )}</option>
        <option value="2" {if not($attribute.contentclass_attribute.content.allowedTargetsInternal|contains('embed'))}disabled="disabled"{/if} {eq( $content.link_type, 2 )|choose( '', 'selected="selected"' )}>{'Embed'|i18n( 'design/standard/class/datatype' )}</option>
        <option value="3" {if not($attribute.contentclass_attribute.content.allowedTargetsInternal|contains('modal'))}disabled="disabled"{/if} {eq( $content.link_type, 3 )|choose( '', 'selected="selected"' )}>{'Modal'|i18n( 'design/standard/class/datatype' )}</option>
    </select>
</div>

<div class="block external-link-block">
    <h2>{'External link'|i18n( 'design/standard/class/datatype' )}:</h2>

    <div class="block inline-block">
        <label for="{$id_base}_url">{'URL'|i18n( 'design/standard/content/datatype' )}:</label>
        <input id="{$id_base}_url" class="box ezcc-{$attribute.object.content_class.identifier} ezcca-{$attribute.object.content_class.identifier}_{$attribute.contentclass_attribute_identifier}" type="text" size="70" name="{$attribute_base}_ngenhancedlink_url_{$attribute.id}" {if eq($content_data.type, 'external')}value="{$attribute.content|wash( xhtml )}"{/if}/>
    </div>

    {* Text. *}
    <div class="block inline-block">
        <label for="{$id_base}_label">{'Label'|i18n( 'design/standard/content/datatype' )}:</label>
        <input id="{$id_base}_label" class="box ezcc-{$attribute.object.content_class.identifier} ezcca-{$attribute.object.content_class.identifier}_{$attribute.contentclass_attribute_identifier}" type="text" size="70" name="{$attribute_base}_ngenhancedlink_label_external_{$attribute.id}" {if eq($content_data.type, 'external')}value="{$content_data.label|wash( xhtml )}"{/if} />
    </div>

    <label for="ecael_target_type_{$attribute.contentclass_attribute.id}">{'Target'|i18n( 'design/standard/class/datatype' )}:</label>
    <select id="eccael_target_type_{$attribute.contentclass_attribute.id}" name="ContentClass_ngenhancedlink_target_external_{$attribute.contentclass_attribute.id}">
        <option value="0" {if not($attribute.contentclass_attribute.content.allowedTargetsExternal|contains('link'))}disabled="disabled"{/if} {if eq($content_data.type, 'external')} {eq( $content_data.target, 'link' )|choose( '', 'selected="selected"' )}{/if}>{'Link'|i18n( 'design/standard/class/datatype' )}</option>
        <option value="1" {if not($attribute.contentclass_attribute.content.allowedTargetsExternal|contains('link_in_new_tab'))}disabled="disabled"{/if} {if eq($content_data.type, 'external')} {eq( $content_data.target, 'link_in_new_tab' )|choose( '', 'selected="selected"' )}{/if}>{'Link in new tab'|i18n( 'design/standard/class/datatype' )}</option>
        <option value="2" {if not($attribute.contentclass_attribute.content.allowedTargetsExternal|contains('embed'))}disabled="disabled"{/if} {if eq($content_data.type, 'external')} {eq( $content_data.target, 'embed' )|choose( '', 'selected="selected"' )}{/if}>{'Embed'|i18n( 'design/standard/class/datatype' )}</option>
        <option value="3" {if not($attribute.contentclass_attribute.content.allowedTargetsExternal|contains('modal'))}disabled="disabled"{/if} {if eq($content_data.type, 'external')} {eq( $content_data.target, 'modal' )|choose( '', 'selected="selected"' )}{/if}>{'Modal'|i18n( 'design/standard/class/datatype' )}</option>
    </select>
</div>
{/let}

{/default}
