parameters:
    ng.fieldtype.enhanced_link.identifier: 'ngenhancedlink'

services:
    Netgen\IbexaFieldTypeEnhancedLink\FieldType\Type:
        parent: ezpublish.fieldType
        public: true
        arguments:
            - '@ezpublish.spi.persistence.content_handler'
            - '@Netgen\IbexaFieldTypeEnhancedLink\FieldType\InternalLinkValidator'
        tags:
            - { name: ezpublish.fieldType, alias: '%ng.fieldtype.enhanced_link.identifier%' }

    Netgen\IbexaFieldTypeEnhancedLink\Persistence\Legacy\FieldValueConverter:
        tags:
            - { name: ezpublish.storageEngine.legacy.converter, alias: '%ng.fieldtype.enhanced_link.identifier%' }

    Netgen\IbexaFieldTypeEnhancedLinkBundle\Form\FieldDefinition\FormMapper:
        arguments:
            - '@ezpublish.api.service.content_type'
            - '@ezpublish.api.service.location'
        tags:
            - { name: ez.fieldFormMapper.definition, fieldType: '%ng.fieldtype.enhanced_link.identifier%' }
            - { name: ez.fieldFormMapper.value, fieldType: '%ng.fieldtype.enhanced_link.identifier%' }

    Netgen\IbexaFieldTypeEnhancedLink\FieldType\SearchFields:
        tags:
            - { name: ezpublish.fieldType.indexable, alias: '%ng.fieldtype.enhanced_link.identifier%' }

    Netgen\IbexaFieldTypeEnhancedLinkBundle\Form\Field\FieldValueType:
        arguments:
            - '@ezpublish.api.service.content'
            - '@ezpublish.api.service.content_type'
            - '@ezpublish.api.service.field_type'
        tags:
            - { name: 'form.type' }

    Netgen\IbexaFieldTypeEnhancedLinkBundle\EventListener\UniversalDiscovery\:
        resource: "../../../bundle/EventListener/UniversalDiscovery/*"
        public: true
        tags: ['kernel.event_subscriber']

    Netgen\IbexaFieldTypeEnhancedLink\FieldType\InternalLinkValidator:
        arguments:
            $contentHandler: '@ezpublish.spi.persistence.content_handler'
            $contentTypeHandler: '@ezpublish.spi.persistence.content_type_handler'

    Netgen\IbexaFieldTypeEnhancedLink\FieldType\UrlStorage\Gateway\DoctrineStorage:
        class: Netgen\IbexaFieldTypeEnhancedLink\FieldType\UrlStorage\Gateway\DoctrineStorage
        arguments: [ '@ezpublish.api.storage_engine.legacy.connection' ]

    Netgen\IbexaFieldTypeEnhancedLink\FieldType\UrlStorage:
        class: Netgen\IbexaFieldTypeEnhancedLink\FieldType\UrlStorage
        arguments:
            - '@Netgen\IbexaFieldTypeEnhancedLink\FieldType\UrlStorage\Gateway\DoctrineStorage'
            - "@?logger"
        tags:
            - { name: ezpublish.fieldType.externalStorageHandler, alias: '%ng.fieldtype.enhanced_link.identifier%' }

    Netgen\IbexaFieldTypeEnhancedLinkBundle\Templating\Twig\Extension\FieldTypeExtension:
        tags:
            - { name: twig.extension }

    Netgen\IbexaFieldTypeEnhancedLinkBundle\Templating\Twig\Extension\FieldTypeRuntime:
        arguments:
            - '@ezpublish.api.repository'
        tags:
            - { name: twig.runtime }

    Netgen\IbexaFieldTypeEnhancedLinkBundle\View\ParameterProvider:
        class: Netgen\IbexaFieldTypeEnhancedLinkBundle\View\ParameterProvider
        arguments:
            - '@ezpublish.api.service.content'
            - '@ezpublish.api.service.field_type'
        tags:
            - { name: ezpublish.fieldType.parameterProvider, alias: '%ng.fieldtype.enhanced_link.identifier%' }
